name: Tests

# on:
#   push:
#     branches:
#       - '*'
#       - '!main'

on:
  push:
    branches-ignore:
      - main
      - master
    paths:
      - "frontend/**"

jobs:
  build:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "frontend/yarn.lock"

      - name: Install dependencies
        run: yarn --cwd frontend install --frozen-lockfile

      - name: Run Tests
        run: yarn --cwd frontend test
        env:
          CI: true
